In [1]:
!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
!pip install tensorboard

 

Looking in indexes: https://download.pytorch.org/whl/cu118
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 857.8/857.8 MB 7.7 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 99.8 MB/s eta 0:00:00ta 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 95.0 MB/s eta 0:00:00:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.7/5.7 MB 82.0 MB/s eta 0:00:00:00:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 103.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.2/133.2 kB 30.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 170.9/170.9 kB 38.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.2/23.2 MB 81.3 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 875.6/875.6 kB 96.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.1/13.1 MB 96.6 MB/s eta 0:00:00a 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 663.9/663.9 MB 10.4 MB/s eta 0:00:0000

In [2]:
!pip install transformers datasets accelerate evaluate bitsandbytes huggingface_hub trl peft

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.7/43.7 kB 4.1 MB/s eta 0:00:00
  Using cached datasets-2.20.0-py3-none-any.whl.metadata (19 kB)
  Using cached evaluate-0.4.2-py3-none-any.whl.metadata (9.3 kB)
  Using cached trl-0.9.6-py3-none-any.whl.metadata (12 kB)
  Using cached PyYAML-6.0.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.1 kB)
  Using cached regex-2024.5.15-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (40 kB)
  Using cached requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
  Using cached tokenizers-0.19.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.7 kB)
  Using cached safetensors-0.4.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.8 kB)
  Using cached tqdm-4.66.4-py3-none-any.whl.metadata (57 kB)
  Using cached pyarrow-17.0.0-cp311-cp311-manylinux_2_28_x86_64.whl.metadata (3.3 kB)
  Using cached pyarrow_hotfix-0.6-py3-none-any.whl.metadata (3.6 kB)
  Using cached di

In [3]:
!pip install ipywidgets

  Using cached ipywidgets-8.1.3-py3-none-any.whl.metadata (2.4 kB)
  Using cached widgetsnbextension-4.0.11-py3-none-any.whl.metadata (1.6 kB)
  Using cached jupyterlab_widgets-3.0.11-py3-none-any.whl.metadata (4.1 kB)
Using cached ipywidgets-8.1.3-py3-none-any.whl (139 kB)
Using cached jupyterlab_widgets-3.0.11-py3-none-any.whl (214 kB)
Using cached widgetsnbextension-4.0.11-py3-none-any.whl (2.3 MB)


In [4]:
!pip install scikit-learn

  Using cached scikit_learn-1.5.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (12 kB)
  Using cached scipy-1.14.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
  Using cached joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
  Using cached threadpoolctl-3.5.0-py3-none-any.whl.metadata (13 kB)
Using cached scikit_learn-1.5.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.3 MB)
Using cached joblib-1.4.2-py3-none-any.whl (301 kB)
Using cached scipy-1.14.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (41.1 MB)
Using cached threadpoolctl-3.5.0-py3-none-any.whl (18 kB)


In [5]:
import json
import pandas as pd
import numpy as np
import torch
import torch.nn.functional as F
import evaluate

from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score, confusion_matrix, classification_report, balanced_accuracy_score, accuracy_score

from datasets import Dataset, DatasetDict
from peft import LoraConfig, prepare_model_for_kbit_training, get_peft_model

from transformers import (
    AutoModelForSequenceClassification,
    AutoTokenizer,
    BitsAndBytesConfig,
    TrainingArguments,
    Trainer,
    DataCollatorWithPadding
)

In [6]:
pairs = []
datasets = ['./data/datasets/ConllAIDA/AIDA-YAGO2-dataset.tsv_nif_labeled_.json',
            './data/datasets/KORE50/KORE_50_DBpedia.ttl_labeled_.json',
            './data/datasets/News/News-100.ttl_labeled_.json',
            './data/datasets/Reuters/Reuters-128.ttl_labeled_.json',
            './data/datasets/RSS/RSS-500.ttl_labeled_.json',
            './data/datasets/medmention/corpus_pubtator.json_labeled_.json'
            ]
for dataset in datasets:
    with open(dataset, 'r') as dataset_file:
        dataset_dict = json.load(dataset_file)
    for dataset_entry in dataset_dict.values():
        doc, labels = dataset_entry.values()
        for label in labels:
            pairs.append({'doc': doc, 'label': label['system']})

In [7]:
df = pd.DataFrame.from_dict(pairs)

In [8]:
df.head()

doc                 label
0  BASEBALL - ORIOLES WIN , YANKEES LOSE .  BALTI...  REL MD (.properties)
1  Granic arrives to sign Croatia-Yugoslavia trea...  REL MD (.properties)
2  BASEBALL - MAJOR LEAGUE STANDINGS AFTER WEDNES...                 TagMe
3  SOCCER - ROMANIA BEAT LITHUANIA IN U-21 QUALIF...      DBpediaSpotlight
4  SOCCER - PLAYERS LEAVE MATCH EARLY TO CATCH PL...  REL MD (.properties)

In [9]:
df['label']=df['label'].astype('category')
df['target']=df['label'].cat.codes

df.head()

doc                 label  \
0  BASEBALL - ORIOLES WIN , YANKEES LOSE .  BALTI...  REL MD (.properties)   
1  Granic arrives to sign Croatia-Yugoslavia trea...  REL MD (.properties)   
2  BASEBALL - MAJOR LEAGUE STANDINGS AFTER WEDNES...                 TagMe   
3  SOCCER - ROMANIA BEAT LITHUANIA IN U-21 QUALIF...      DBpediaSpotlight   
4  SOCCER - PLAYERS LEAVE MATCH EARLY TO CATCH PL...  REL MD (.properties)   

   target  
0       6  
1       6  
2       9  
3       2  
4       6

In [10]:
df['label'].cat.categories

Index(['Babelfy', 'CLOCQ', 'DBpediaSpotlight', 'Falcon 2.0', 'OpenTapioca',
       'REL', 'REL MD (.properties)', 'Refined MD (.properties)',
       'Spacy MD (.properties)', 'TagMe', 'TextRazor'],
      dtype='object')

In [11]:
category_map = {code: category for code, category in enumerate(df['label'].cat.categories)}
category_map

{0: 'Babelfy',
 1: 'CLOCQ',
 2: 'DBpediaSpotlight',
 3: 'Falcon 2.0',
 4: 'OpenTapioca',
 5: 'REL',
 6: 'REL MD (.properties)',
 7: 'Refined MD (.properties)',
 8: 'Spacy MD (.properties)',
 9: 'TagMe',
 10: 'TextRazor'}

In [12]:
train_end_point = int(df.shape[0]*0.6)
val_end_point = int(df.shape[0]*0.8)
df_train = df.iloc[:train_end_point,:]
df_val = df.iloc[train_end_point:val_end_point,:]
df_test = df.iloc[val_end_point:,:]
print(df_train.shape, df_test.shape, df_val.shape)



(4193, 3) (1398, 3) (1398, 3)


In [13]:
dataset_train = Dataset.from_pandas(df_train.drop('label',axis=1))
dataset_val = Dataset.from_pandas(df_val.drop('label',axis=1))
dataset_test = Dataset.from_pandas(df_test.drop('label',axis=1))

In [14]:
dataset_train_shuffled = dataset_train.shuffle(seed=42)  

In [15]:
dataset = DatasetDict({
    'train': dataset_train_shuffled,
    'val': dataset_val,
    'test': dataset_test
})
dataset

DatasetDict({
    train: Dataset({
        features: ['doc', 'target'],
        num_rows: 4193
    })
    val: Dataset({
        features: ['doc', 'target'],
        num_rows: 1398
    })
    test: Dataset({
        features: ['doc', 'target'],
        num_rows: 1398
    })
})

In [16]:
dataset['train']

Dataset({
    features: ['doc', 'target'],
    num_rows: 4193
})

In [17]:
df_train.target.value_counts(normalize=True)

target
6     0.357978
10    0.177439
9     0.126163
7     0.107083
0     0.075841
2     0.067732
8     0.063201
4     0.019079
5     0.002862
1     0.001669
3     0.000954
Name: proportion, dtype: float64

In [18]:
class_weights=(1/df_train.target.value_counts(normalize=True).sort_index()).tolist()
class_weights=torch.tensor(class_weights)
class_weights=class_weights/class_weights.sum()
class_weights

tensor([0.0062, 0.2827, 0.0070, 0.4948, 0.0247, 0.1649, 0.0013, 0.0044, 0.0075,
        0.0037, 0.0027])

In [36]:
model_name = "unsloth/llama-3-8b"
model_name = "./saved_model/"

In [37]:
quantization_config = BitsAndBytesConfig(
    load_in_4bit = True,
    bnb_4bit_quant_type = 'nf4', 
    bnb_4bit_use_double_quant = True, 
    bnb_4bit_compute_dtype = torch.bfloat16 
)

In [38]:

lora_config = LoraConfig(
    r = 16, 
    lora_alpha = 8, 
    target_modules = ['q_proj', 'k_proj', 'v_proj', 'o_proj'],
    lora_dropout = 0.05, 
    bias = 'none', 
    task_type = 'SEQ_CLS'
)

In [39]:

model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    quantization_config=quantization_config,
    num_labels=11
)


`low_cpu_mem_usage` was None, now set to True since model is quantized.


Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Some weights of LlamaForSequenceClassification were not initialized from the model checkpoint at unsloth/llama-3-8b and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [40]:
model = prepare_model_for_kbit_training(model)
     

In [41]:
model = get_peft_model(model, lora_config)

In [42]:
tokenizer = AutoTokenizer.from_pretrained(model_name, add_prefix_space=True)

tokenizer.pad_token_id = tokenizer.eos_token_id
tokenizer.pad_token = tokenizer.eos_token

In [43]:

model.config.pad_token_id = tokenizer.pad_token_id
model.config.use_cache = False
model.config.pretraining_tp = 1

In [44]:
sentences = df_test.doc.tolist()

In [46]:
from tqdm import tqdm
batch_size = 64  

all_outputs = []

for i in tqdm(range(0, len(sentences), batch_size)):
    batch_sentences = sentences[i:i + batch_size]
    inputs = tokenizer(batch_sentences, return_tensors="pt", padding=True, truncation=True, max_length=512)
    inputs = {k: v.to('cuda' if torch.cuda.is_available() else 'cpu') for k, v in inputs.items()}
    with torch.no_grad():
        outputs = model(**inputs)
        all_outputs.append(outputs['logits'])


100%|██████████| 22/22 [13:00<00:00, 35.46s/it]


In [25]:
import pickle
with open("all_outputs.pickel", 'rb') as backup_all_outputs:
    all_outputs = pickle.load(backup_all_outputs)

In [47]:
final_outputs = torch.cat(all_outputs, dim=0)

In [48]:
final_outputs.argmax(axis=1)

tensor([10,  4,  6,  ...,  7,  4,  7], device='cuda:0')

In [49]:

df_test['predictions']=final_outputs.argmax(axis=1).cpu().numpy()

df_test['predictions'].value_counts()

/tmp/ipykernel_1019210/3448790646.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test['predictions']=final_outputs.argmax(axis=1).cpu().numpy()


predictions
7     323
4     320
10    295
3     189
2      81
1      72
0      49
8      28
9      20
6      15
5       6
Name: count, dtype: int64

In [50]:
df_test['predictions']=df_test['predictions'].apply(lambda l:category_map[l])
df_test['predictions']

/tmp/ipykernel_1019210/4293232383.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test['predictions']=df_test['predictions'].apply(lambda l:category_map[l])


5591                   TextRazor
5592                 OpenTapioca
5593        REL MD (.properties)
5594                   TextRazor
5595                       TagMe
                  ...           
6984      Spacy MD (.properties)
6985    Refined MD (.properties)
6986    Refined MD (.properties)
6987                 OpenTapioca
6988    Refined MD (.properties)
Name: predictions, Length: 1398, dtype: object

In [51]:
def get_performance_metrics(df_test):
  y_test = df_test.label
  y_pred = df_test.predictions

  print(confusion_matrix(y_test, y_pred))
  print(classification_report(y_test, y_pred))
  print("Balanced Accuracy:", balanced_accuracy_score(y_test, y_pred))
  print("Accuracy:", accuracy_score(y_test, y_pred))
     

In [52]:
get_performance_metrics(df_test)

[[ 12  12   9  20  63   1   4  53   1   7  65]
 [  0   0   0   0   0   0   0   0   0   0   0]
 [ 10  14  10  33  59   1   3  62   5   4  61]
 [  0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   1   2   1   0   0   4   1   0   2]
 [  0   0   0   0   2   0   0   0   0   0   1]
 [  0   3   3   7   8   0   0  10   0   0   5]
 [ 17  27  22  72 101   2   3 100   7   1  87]
 [ 10  16  36  55  86   2   5  94  14   8  74]]
                          precision    recall  f1-score   support

                 Babelfy       0.24      0.05      0.08       247
                   CLOCQ       0.00      0.00      0.00         0
        DBpediaSpotlight       0.12      0.04      0.06       262
              Falcon 2.0       0.00      0.00      0.00         0
             OpenTapioca       0.00      0.00      0.00         0
                     REL       0.00      0.00      0.00         0
    REL MD (.proper

/local/users/unjde/analysis/.conda/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/local/users/unjde/analysis/.conda/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/local/users/unjde/analysis/.conda/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/

In [53]:

MAX_LEN = 512
col_to_delete = ['doc']

def llama_preprocessing_function(examples):
    return tokenizer(examples['doc'], truncation=True, max_length=MAX_LEN)

tokenized_datasets = dataset.map(llama_preprocessing_function, batched=True, remove_columns=col_to_delete)
tokenized_datasets = tokenized_datasets.rename_column("target", "label")
tokenized_datasets.set_format("torch")

Map:   0%|          | 0/4193 [00:00<?, ? examples/s]

Map:   0%|          | 0/1398 [00:00<?, ? examples/s]

Map:   0%|          | 0/1398 [00:00<?, ? examples/s]

In [54]:
collate_fn = DataCollatorWithPadding(tokenizer=tokenizer)

In [55]:

def compute_metrics(eval_pred):
    predictions, labels = eval_pred
    predictions = np.argmax(predictions, axis=1)
    return {'balanced_accuracy' : balanced_accuracy_score(predictions, labels),'accuracy':accuracy_score(predictions,labels)}


In [56]:
     


class CustomTrainer(Trainer):
    def __init__(self, *args, class_weights=None, **kwargs):
        super().__init__(*args, **kwargs)
        if class_weights is not None:
            self.class_weights = torch.tensor(class_weights, dtype=torch.float32).to(self.args.device)
        else:
            self.class_weights = None

    def compute_loss(self, model, inputs, return_outputs=False):
        labels = inputs.pop("labels").long()

        outputs = model(**inputs)

        logits = outputs.get('logits')

        if self.class_weights is not None:
            loss = F.cross_entropy(logits, labels, weight=self.class_weights)
        else:
            loss = F.cross_entropy(logits, labels)

        return (loss, outputs) if return_outputs else loss

     


In [61]:

training_args = TrainingArguments(
    output_dir = 'sentiment_classification',
    learning_rate = 1e-4,
    per_device_train_batch_size = 16,
    per_device_eval_batch_size = 16,
    num_train_epochs = 2,
    weight_decay = 0.01,
    evaluation_strategy = 'epoch',
    save_strategy = 'epoch',
    load_best_model_at_end = True
)
     

/local/users/unjde/analysis/.conda/lib/python3.11/site-packages/transformers/training_args.py:1525: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(


In [62]:


trainer = CustomTrainer(
    model = model,
    args = training_args,
    train_dataset = tokenized_datasets['train'],
    eval_dataset = tokenized_datasets['val'],
    tokenizer = tokenizer,
    data_collator = collate_fn,
    compute_metrics = compute_metrics,
    class_weights=class_weights,
)
     


/tmp/ipykernel_1019210/3515193827.py:5: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  self.class_weights = torch.tensor(class_weights, dtype=torch.float32).to(self.args.device)


In [63]:
train_result = trainer.train()

/local/users/unjde/analysis/.conda/lib/python3.11/site-packages/torch/nn/parallel/parallel_apply.py:79: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.device(device), torch.cuda.stream(stream), autocast(enabled=autocast_enabled):
/local/users/unjde/analysis/.conda/lib/python3.11/site-packages/torch/_dynamo/eval_frame.py:600: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)


In [54]:
from tqdm import tqdm

def make_predictions(model,df_test):

  sentences = df_test.doc.tolist()
  batch_size = 8  
  all_outputs = []

  for i in tqdm(range(0, len(sentences), batch_size)):
      batch_sentences = sentences[i:i + batch_size]

      inputs = tokenizer(batch_sentences, return_tensors="pt", padding=True, truncation=True, max_length=512)

      inputs = {k: v.to('cuda' if torch.cuda.is_available() else 'cpu') for k, v in inputs.items()}

      with torch.no_grad():
          outputs = model(**inputs)
          all_outputs.append(outputs['logits'])
  final_outputs = torch.cat(all_outputs, dim=0)
  df_test['predictions']=final_outputs.argmax(axis=1).cpu().numpy()
  df_test['predictions']=df_test['predictions'].apply(lambda l:category_map[l])


make_predictions(model,df_test)
     

100%|██████████| 175/175 [22:43<00:00,  7.79s/it]
/tmp/ipykernel_3256520/2639498767.py:31: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test['predictions']=final_outputs.argmax(axis=1).cpu().numpy()
/tmp/ipykernel_3256520/2639498767.py:32: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test['predictions']=df_test['predictions'].apply(lambda l:category_map[l])


In [55]:
get_performance_metrics(df_test)

Confusion Matrix:
[[ 83  46   0   0   0  63  55]
 [ 84  39   0   0   0  92  47]
 [  4   1   0   0   0   4   2]
 [  1   0   0   0   0   1   1]
 [ 10   2   0   0   0  18   6]
 [ 58  54   0   0   0 249  78]
 [ 71  58   0   0   0 183  88]]

Classification Report:
                          precision    recall  f1-score   support

                 Babelfy       0.27      0.34      0.30       247
        DBpediaSpotlight       0.20      0.15      0.17       262
    REL MD (.properties)       0.00      0.00      0.00        11
Refined MD (.properties)       0.00      0.00      0.00         3
  Spacy MD (.properties)       0.00      0.00      0.00        36
                   TagMe       0.41      0.57      0.47       439
               TextRazor       0.32      0.22      0.26       400

                accuracy                           0.33      1398
               macro avg       0.17      0.18      0.17      1398
            weighted avg       0.30      0.33      0.31      1398

Balanced Ac

/local/users/unjde/analysis/analysis/combining_linking_techniques_analysis/.conda/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/local/users/unjde/analysis/analysis/combining_linking_techniques_analysis/.conda/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/local/users/unjde/analysis/analysis/combining_linking_techniques_analysis/.conda/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in

In [51]:
metrics = train_result.metrics
max_train_samples = len(dataset_train)
metrics["train_samples"] = min(max_train_samples, len(dataset_train))
trainer.log_metrics("train", metrics)
trainer.save_metrics("train", metrics)
trainer.save_state()

***** train metrics *****
  epoch                    =         2.0
  total_flos               = 109419442GF
  train_loss               =      1.7293
  train_runtime            =  6:09:19.29
  train_samples            =        4193
  train_samples_per_second =       0.378
  train_steps_per_second   =       0.189


In [52]:
trainer.save_model("saved_model")